/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "Esp8266_Interface.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Esp8266_Command, Esp8266_Command, AUTO)


PB_BIND(Esp8266_Full_Request, Esp8266_Full_Request, AUTO)


PB_BIND(Esp8266_Metrics, Esp8266_Metrics, AUTO)



/* @@protoc_insertion_point(eof) */
