/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "Esp8266_Interface.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esp8266_Esp8266_Command, esp8266_Esp8266_Command, AUTO)


PB_BIND(esp8266_Esp8266_Metrics, esp8266_Esp8266_Metrics, AUTO)





/* On some platforms (such as AVR), double is really float.
 * Using double on these platforms is not directly supported
 * by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
