// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EspEvent.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Esp8266Event struct {
	Stat                 *int32   `protobuf:"varint,1,req,name=stat" json:"stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Esp8266Event) Reset()         { *m = Esp8266Event{} }
func (m *Esp8266Event) String() string { return proto.CompactTextString(m) }
func (*Esp8266Event) ProtoMessage()    {}
func (*Esp8266Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_df7e1f92e962ba78, []int{0}
}

func (m *Esp8266Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Esp8266Event.Unmarshal(m, b)
}
func (m *Esp8266Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Esp8266Event.Marshal(b, m, deterministic)
}
func (m *Esp8266Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Esp8266Event.Merge(m, src)
}
func (m *Esp8266Event) XXX_Size() int {
	return xxx_messageInfo_Esp8266Event.Size(m)
}
func (m *Esp8266Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Esp8266Event.DiscardUnknown(m)
}

var xxx_messageInfo_Esp8266Event proto.InternalMessageInfo

func (m *Esp8266Event) GetStat() int32 {
	if m != nil && m.Stat != nil {
		return *m.Stat
	}
	return 0
}

func init() {
	proto.RegisterType((*Esp8266Event)(nil), "pb.Esp8266Event")
}

func init() { proto.RegisterFile("EspEvent.proto", fileDescriptor_df7e1f92e962ba78) }

var fileDescriptor_df7e1f92e962ba78 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x73, 0x2d, 0x2e, 0x70,
	0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52,
	0xe2, 0xe2, 0x71, 0x2d, 0x2e, 0xb0, 0x30, 0x32, 0x33, 0x03, 0xcb, 0x08, 0x09, 0x71, 0xb1, 0x14,
	0x97, 0x24, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x06, 0x81, 0xd9, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x52, 0x57, 0xbe, 0x38, 0x00, 0x00, 0x00,
}
